version: '3'
services:
  databse:
    image: mysql:8
    container_name: 'db-test'
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./config/mysql/mysql.conf.d:/etc/mysql/mysql.conf.d
    ports:
      - "3306:3306"
  web:
    image: nginx
    container_name: 'web-test'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../:/var/www/html
      - ./data/var/log/nginx:/var/log/nginx
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    environment:
      - NGINX_HOST=dev.loc
      - NGINX_PORT=80
  php:
    build:
      context: .
      dockerfile: build/php/Dockerfile
    container_name: 'php-test'
    volumes:
      - ../:/var/www/html
      - ./config/fpm/conf.d:/usr/local/etc/php/conf.d
